// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmFF9CUuscWlxW3TxaUH4Nyi8NfPXK_bg',
    appId: '1:670787980231:web:51c33acd95b743dfba27e2',
    messagingSenderId: '670787980231',
    projectId: 'ulma-a8e18',
    authDomain: 'ulma-a8e18.firebaseapp.com',
    storageBucket: 'ulma-a8e18.appspot.com',
    measurementId: 'G-K2NH0X6JR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoQyF7D0VNg01bRrIwWFWuofumcYkLLws',
    appId: '1:670787980231:android:5161dde9f16ba395ba27e2',
    messagingSenderId: '670787980231',
    projectId: 'ulma-a8e18',
    storageBucket: 'ulma-a8e18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzYl64cz7mKxl4YVIeDGagpDJJHUlF86k',
    appId: '1:670787980231:ios:75015cde996b307aba27e2',
    messagingSenderId: '670787980231',
    projectId: 'ulma-a8e18',
    storageBucket: 'ulma-a8e18.appspot.com',
    iosBundleId: 'com.example.ulmaAssgn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzYl64cz7mKxl4YVIeDGagpDJJHUlF86k',
    appId: '1:670787980231:ios:75015cde996b307aba27e2',
    messagingSenderId: '670787980231',
    projectId: 'ulma-a8e18',
    storageBucket: 'ulma-a8e18.appspot.com',
    iosBundleId: 'com.example.ulmaAssgn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmFF9CUuscWlxW3TxaUH4Nyi8NfPXK_bg',
    appId: '1:670787980231:web:13ec0918fb3e6647ba27e2',
    messagingSenderId: '670787980231',
    projectId: 'ulma-a8e18',
    authDomain: 'ulma-a8e18.firebaseapp.com',
    storageBucket: 'ulma-a8e18.appspot.com',
    measurementId: 'G-8TDB1VC304',
  );
}
